### PR TITLE
Suggestion feature

### PR DESCRIPTION
**Pull request by ohbarye**
## Issue

closes https://github.com/reviewdog/action-rubocop/issues/28

## Changes

This pull request adds a feature to make the reviewdog create a comment with a suggestion. Like below:

image

Here's an example pull request to utilize the feature: https://github.com/ohbarye/rubocop-suggestion-example/pull/4

## Design

First, I added `RdjsonFormatter` class in Ruby so that rubocop gets able to generate [rdformat](https://github.com/reviewdog/reviewdog/tree/d3768e5ebc66846ccb6c1c0a871ae049b1e7e97e/proto/rdf) JSON. I followed some instructions to implement a new formatter, e.g. https://docs.rubocop.org/rubocop/formatters.html, https://www.rubydoc.info/gems/rubocop/RuboCop/Formatter/BaseFormatter.

Second, I added a test for `RdjsonFormatter`. I just followed the way of https://github.com/reviewdog/action-eslint. Add test data, shell script, and CI setting.

### CODE REVIEW

**Comment by gagalago** [comment]
awesome. can be interesting to upstream the `RdjsonFormatter` at some point to gain fix and feedback from a bigger community but I suppose that for now it better to keep it in this repository to have it faster released with reviewdog.

**Comment by ohbarye** [comment]
@mgrachev @adnikiforov I'd be glad if you'd review this when you have time. 🙏

**Review by gagalago — APPROVED** [review]

**Comment by mgrachev** [comment]
@ohbarye I'm sorry for the long answer. I was on vacation.

Thank you for your contribution! Please resolve a conflict 🙏

**Review by mgrachev — APPROVED** [review]

**Comment by mgrachev** [comment]
@ohbarye Thanks a lot for your help 💚

**Pull request merged**
