### PR TITLE
Add input to skip install

### LINKED ISSUE #42: Add ability to skip install of rubocop and extensions
If a previous step in our action like `setup-ruby` already installs rubocop and the required extensions based on `Gemfile` there should be no need to do it again here. It would be nice to be able to skip the rubocop install and just run it.

```yml
- name: Setup Ruby
   uses: ruby/setup-ruby@v1
     with:
       bundler-cache: true
```

### PR DESCRIPTION
**Pull request by szechyjs**
I think this should fix #42.

### CODE REVIEW

**Comment by adnikiforov** [comment]
I think theoretically it's possible to grep `bundle list` for installed rubocop, so we don't need to use param for skipping rubocop install. No sure if it is should be on by default. @mgrachev WDYT?

**Comment by igas** [comment]
Would love to see it's implemented. We actually have our own cops as a gem in monorepo, so we need to use `bundle exec` for it.

**Comment by mgrachev** [comment]
@szechyjs Thank you for your contribution 👍

Sorry for the long response. Could you please add tests to ensure that everything works in different options?
You can take https://github.com/dotenv-linter/action-dotenv-linter/blob/master/.github/workflows/ci.yml as an example.

**Comment by mgrachev** [comment]
I'll close this PR because #47 was merged.

**Pull request closed without merging**
